name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    
    - name: Compile
      run: mvn compile
    
    - name: Test with Coverage
      run: mvn test
    
    - name: Package
      run: mvn package
      if: success()
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifacts
        path: "*/target/*.jar"
    
    - name: Workflow Status Notification
      if: always()
      run: |
        echo "🔔 WORKFLOW NOTIFICATION:"
        echo "   Workflow: ${{ github.workflow }}"
        echo "   Status: ${{ job.status }}"
        echo "   URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        # Try to notify MCP server if URL is configured
        if [ -n "${{ secrets.MCP_WEBHOOK_URL }}" ]; then
          curl -X POST "${{ secrets.MCP_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: workflow_run" \
            -d '{
              "workflow_run": {
                "name": "${{ github.workflow }}",
                "status": "completed",
                "conclusion": "${{ job.status }}",
                "html_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }' || echo "Failed to notify MCP server"
        else
          echo "No MCP_WEBHOOK_URL configured - add as repository secret"
        fi